### ISSUE TITLE
Loading jpg png failing

### ISSUE THREAD

**Issue by surfingnirvana** [sapiensl/neurotile#1]
ca:0/task:0/device:GPU:0 with 9442 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6
Warning: could not load base image with name gold.jpg, skipping...
Warning: could not load base image with name honeys3-gigapixel.png, skipping...
Warning: could not load base image with name gold.jpg, skipping...
Warning: could not load base image with name honeys3-gigapixel.png, skipping...
Traceback (most recent call last):
  File "C:\NEURAL\neurotile-master\neurotile_gui.py", line 4, in <module>
    import neurotile as nt
  File "C:\NEURAL\neurotile-master\neurotile.py", line 1014, in <module>
    testImage = loadTestImage(256)
  File "C:\NEURAL\neurotile-master\neurotile.py", line 346, in loadTestImage
    posX = (baseImage.shape[1] - k)//2
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by sapiensl** [comment]
Hi! Nice to see someone here!
The neurotile GUI is very much WIP and does not work as expected.
I will comment out some confusing code and write instructions on how to get started with this in the coming 1-2 weeks when I have a bit more time on my hand.

You can try these steps with neurotile.py while you wait for this to happen:
- create a folder structure next to neurotile.py like this:
    - neurotile.py
    - projects/
        - default/
            - images/
                - put your images here (must be same size, 512px recommended)

run neurotile.py in your console and write these commands:

setProject("RANDOMPROJECTNAME") #this will copy the content of the default project to a new folder
stdLearning()

Now neurotile creates a new set of models and trains it as specified in the SeamlessGAN paper. Afterwards it saves the project data. you can check how well it is going by looking at the intermediate output images that are generated every 500ish training steps.

To export a finished texture stack...:
- run neurotile_gui.py
- click export
- load the project folder you just trained
- find a crop of the input image that results in a pretty output
- click export

if you want to write your own learning process just copy all you need from stdLearning. In the next update I will also include my optimized learning process that nearly halves the amount of work needed for a suitable output.

Hope that helps for now.

EDIT: added export instructions

**Comment by surfingnirvana** [comment]
Thank you but it does not fix the error. posX = (baseImage.shape[1] - k)//2
AttributeError: 'NoneType' object has no attribute 'shape'
I'm running it on windows. Maybe there is the issue.

**Comment by sapiensl** [comment]
Okay. I am doing this on Windows too so that is perfectly fine.
The error you are seeing happens when something went wrong loading the input images.
Maybe you can find out what the matter is with these. Please call back when you got something. In the meantime I will see how I can make image loading more robust.

**Comment by sapiensl** [comment]
One idea to debug this issue: You might want to run loadImageStack(...) without try and except to see what the real issue is. Can you please post the results if you do so?

Also, can you check if the images are copied to your project directory? It seems that the copy process is currently hard-coded to only copy images called "albedo" and "normal", which I have already fixed and will push in a few days with other fixes and updates.

**Comment by surfingnirvana** [comment]
This is the real issue:

Traceback (most recent call last):
  File "C:\NEURAL\neurotile-master\neurotile.py", line 1008, in <module>
    baseImage = loadImageStack()
  File "C:\NEURAL\neurotile-master\neurotile.py", line 839, in loadImageStack
    image = tf.image.crop_to_bounding_box(image, 0,0, image.getbbox()[3], image.getbbox()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=512x512 at 0x1BE888569D0>) with an unsupported type (<class 'PIL.JpegImagePlugin.JpegImageFile'>) to a Tensor.

**Comment by sapiensl** [comment]
Hey!
I cannot seem to be able to reproduce this issue, all images I threw into the program were consumed without a hitch.
Therefore I will give you my setup so you can experiment around with version numbers and stuff.

- Python 3.8.0
- Tensorflow 2.8.0
- Tensorflow Addons 0.16.1
- Pillow 8.4.0
- Cuda 11.2
- cudNN 8.1

It probably does not have anything to do with Cuda/cudNN, but maybe there is an issue with incompatibilities between your tf version and pillow?

If you feel confident enough you could rewrite the loader to have a version that works on your system. The output is a stack of all loaded textures, in one big tensor. For example, 2 RGBA pngs at 512x512 pixel are stripped of their alpha channel and then stacked to become one big 512x512x6 elements tensor.

If you find a solution for yourself or have more info, please let me know.
Also I just pushed a new commit that includes optimizedLearning() and other improvements.
